update ps1 cmd

diff --git a/rcfiles/bashrc b/rcfiles/bashrc
--- a/rcfiles/bashrc
+++ b/rcfiles/bashrc
@@ -11,17 +11,8 @@ alias copy='head -c -1 | xclip -selection clipboard'
 alias ports='sudo netstat -tunpl'
 alias rc="code $HOME/.bashrc"
 
-function ps1() {
-    # ps + grep
-    if [[ $# -eq 0 ]]; then
-        echo "Missing search regex"
-        return 1
-    fi
-    
-    ps -eo pid,user,cmd | grep -v grep | grep $@
-}
 
-function path() {
+function path {
     if [[ $# -eq 0 ]]; then
         p=$(pwd)
     else
@@ -32,7 +23,7 @@ function path() {
     echo $p | copy
 }
 
-function where() {
+function where {
     # show the real file path of a command
     if [[ $# -eq 0 ]]; then
         echo "Missing argument: command"
@@ -41,19 +32,20 @@ function where() {
     fi
 }
 
-
+# ===== env.sh files
 ENV='ENV_FILE=$BASH_SOURCE && ENV_DIR=$(dirname $BASH_SOURCE) && cd $ENV_DIR'
 
-function home() {
+function home {
     # cd to the directory containing env.sh
     if [ -z ${ENV_FILE+x} ]; then
         echo "No configed env.sh"
         return 1
     fi
+
     cd "$ENV_DIR"
 }
 
-function e() {
+function e {
     # edit the current env.sh
     if [ -z ${ENV_FILE+x} ]; then
         echo "No configed env.sh"
@@ -62,7 +54,51 @@ function e() {
     code $ENV_FILE
 }
 
-function pskill() {
+# ===== END of env.sh files
+
+function ps1 {
+    # ps + grep
+    if [[ $# -eq 0 ]]; then
+        echo "Missing search regex"
+        return 1
+    fi
+    
+    ps -eo pid,user,cmd | grep -v grep | grep $@
+}
+
+# print pids of filtered processes
+# often used after ps1
+# ps1: print all processed
+# ps1 <filter>: filtered processed
+# ps1 <filter> 1: show pids
+# ps1 <filter> 2: kill filtered processs
+function ps1 {
+    local filter="${1:-''}"
+    (( $# >= 1 )) && filter=$1
+
+    (($# == 1)); just_filter=$?
+
+    [[ $# -ge 2 && "$1" == 1 ]]; show_pids=$?
+    [[ $# -ge 2 && "$1" == 2 ]]; kill_procs=$?
+
+    if [[ $# == 0 ]]; then
+        ps -ef
+    elif [[ $# == 1 ]]; then
+        filter=$1
+        ps -ef | grep -v grep | grep "$filter"
+    else
+        if [[ $2 == "pid" || $2 == "p" ]]; then
+            ps -ef | grep -v grep | grep "$filter" | awk '{print $2}'
+        elif [[ $2 == "kill" || $2 == "k" ]]; then
+            ps -ef | grep -v grep | grep "$filter" | awk '{print $2}' | xargs kill
+        else
+            echo "Unrecognized subcmd: $2"
+        fi
+    fi
+}
+
+
+function pscmd {
     if [[ $# -eq 0 ]]; then
         echo "Missing argument: command"
         return 1
@@ -200,6 +236,7 @@ _git_ps1 ()
 PS1='\n\e[;1;33m\u\e[;1;35m@\e[;1;32m\h \e[;1;36m\w\e[;1;33m$(_git_ps1)\n\[\033[00m\]\$ '
 
 [[ -f ~/.bashrc.local ]] && . ~/.bashrc.local
+
 
 # ===============================================================================================
 
